spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/exchange_information_db
    username: eis
    password: eis
    driverClassName: org.postgresql.Driver
  liquibase:
        change-log: classpath:db/changelog/db.changelog-master.yaml
        enabled: true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate